import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NotificationProvider from "@/components/AppNotifications/NotificationProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" data-scroll-behavior="smooth" suppressHydrationWarning
		      className={`${geistSans.variable} ${geistMono.variable} no-scrollbar`}
		>
			<body
				suppressHydrationWarning
				className="antialiased m-0"
			>
				<NotificationProvider />
				{children}
			</body>
		</html>
	);
}
