'use client';

import React, { useState } from 'react';
import { ArrowLeft, Sparkles } from 'lucide-react';
import { useRouter } from 'next/navigation';
import SummaryCard from '@/components/Files/SummaryCard';
import FlashCard from '@/components/Files/FlashCard';

export default function AIAnalysisView() {
    const router = useRouter();
    const gradientPalette = [
        { from: '#fe3d6c', to: '#fc9995' }, 
        { from: '#3fff7c', to: '#3ffbe0' }, 
        { from: '#6b2cf5', to: '#d450e6' }, 
        { from: '#2f80ff', to: '#3ccbff' }, 
        { from: '#ff4ba7', to: '#ffda64' }, 
        { from: '#a1ffd9', to: '#f3ff77' },
    ];

    const [summary] = useState(
        "This text represents an intelligent summary generated by the Gemini model for the attached file. The document includes a comprehensive analysis of the inputted data, where the results demonstrated a significant performance increase of over 15% compared to previous periods. It is highly recommended to focus on optimizing user interfaces and utilizing reusable components to reduce load times. Additionally, the report highlights the importance of enabling button tooltips and enhancing the overall user experience using modern animation techniques alongside consistent color gradients to ensure a comfortable and visually engaging experience."
    );

    const [flashCards] = useState([
        { 
            id: 1, 
            question: "What is the primary advantage of using the Next.js App Router?", 
            answer: "It provides built-in support for Server Components, automatic performance optimization, and a simplified file-system based routing mechanism." 
        },
        { 
            id: 2, 
            question: "How do we create a reusable component in React?", 
            answer: "By isolating the UI logic into an independent file and making it accept dynamic data via Props instead of hardcoding values." 
        },
        { 
            id: 3, 
            question: "What is the purpose of the transform-style property in flip animations?", 
            answer: "It allows child elements to preserve their 3D positioning and depth when the parent container is rotated." 
        },
        { 
            id: 4, 
            question: "Why do we use color gradients in UI cards?", 
            answer: "They provide visual depth, making the user interface feel more lively, modern, and engaging compared to standard solid colors." 
        },
        { 
            id: 5, 
            question: "What is the primary use case for Client Components in Next.js?", 
            answer: "They are used when user interactivity is required, such as handling state hooks (useState, useEffect) or listening to UI events like onClick." 
        },
        { 
            id: 6, 
            question: "How does the Gemini tool assist in file analysis?", 
            answer: "It parses file content, comprehends the context, extracts key insights accurately, and dynamically generates interactive Q&As based on the data." 
        }
    ]);

    return (
        <div className="p-6 ">

            <div className="flex items-center justify-between mb-8 border-b border-gray-200 pb-4">
                <div className="flex items-center gap-3">
                    <div className="p-2 bg-purple-50 text-purple-600 rounded-xl">
                        <Sparkles size={30} />
                    </div>

                    <div>
                        <h1 className="text-2xl font-bold text-black">
                            Artificial intelligence analysis (Gemini AI)
                        </h1>

                        <p className="text-lg text-gray-500 mt-0.5">
                            Review of the file and interactive flashcards
                        </p>
                    </div>
                </div>
        
                <div className="flex justify-end mb-2">
                    <button 
                        onClick={() => router.push("/files")}
                        className="p-1 rounded-full border border-gray-300 bg-white hover:bg-gray-50 text-gray-700 transition-colors"
                    >
                        <ArrowLeft className="w-8 h-8 rotate-180" />
                    </button>
                </div>
            </div>

            <div className="mb-10">
                <SummaryCard summaryText={summary} />
            </div>

            <div>
                <h2 className="text-2xl font-bold text-black mb-4">
                    Flash Cards
                </h2>
        
                <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
                    {flashCards.map((card, index) => (
                        <FlashCard 
                            key={card.id} 
                            card={card} 
                            gradient={gradientPalette[index % gradientPalette.length]} 
                        />
                    ))}
                </div>
            </div>

            <div className='p-4 mt-6 flex justify-center'>
                <button className='btn'>
                    New Flash Cards
                </button>
            </div>

        </div>
    );
}