// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyBuddy.Infrastructure.Context;

#nullable disable

namespace StudyBuddy.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412153435_Rename friend and client user in friend to first and second")]
    partial class Renamefriendandclientuserinfriendtofirstandsecond
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticleTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("pk_Article");

                    b.HasIndex("ArticleTypeId");

                    b.HasIndex("ClientUserId");

                    b.ToTable("Article", (string)null);
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.ArticleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("pk_ArticleType");

                    b.ToTable("ArticleType", (string)null);
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.AspNetRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.AspNetUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.AspNetUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("pk_City");

                    b.HasIndex("CountryId");

                    b.ToTable("City", (string)null);
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.ClientFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Bin")
                        .HasColumnType("BLOB")
                        .HasColumnName("bin");

                    b.Property<int>("ClientUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("pk_ClientFile");

                    b.HasIndex("ClientUserId");

                    b.ToTable("ClientFile", (string)null);
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.ClientUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MajorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("BLOB");

                    b.Property<int?>("UniversityId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("pk_ClientUser");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("MajorId");

                    b.HasIndex("UniversityId");

                    b.HasIndex("UserId");

                    b.ToTable("ClientUser", (string)null);
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.ClientUserAvailableDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientUserId");

                    b.HasIndex("DayId");

                    b.ToTable("ClientUserAvailableDays");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.ClientUserGroupChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupChatId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("pk_ClientUserGroupChat");

                    b.HasIndex("ClientUserId");

                    b.HasIndex("GroupChatId");

                    b.ToTable("ClientUserGroupChat", (string)null);
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.ClientUserLikeFeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FeedId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientUserId");

                    b.HasIndex("FeedId");

                    b.ToTable("ClientUserLikeFeeds");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.ClientUserSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("pk_ClientUserSkill");

                    b.HasIndex("ClientUserId");

                    b.HasIndex("SkillId");

                    b.ToTable("ClientUserSkill", (string)null);
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("pk_Country");

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Days");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("pk_Event");

                    b.HasIndex("ClientUserId");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Feed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShareCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("pk_Feed");

                    b.HasIndex("ClientUserId");

                    b.ToTable("Feed", (string)null);
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.FeedReplay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FeedId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("pk_FeedReplay");

                    b.HasIndex("FeedId");

                    b.ToTable("FeedReplay", (string)null);
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Friend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FirstFriendId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstFriendId1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SecondFriendId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("pk_Friend");

                    b.HasIndex("FirstFriendId");

                    b.HasIndex("FirstFriendId1");

                    b.ToTable("Friend", (string)null);
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.FriendRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FriendId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsAccepted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("pk_FriendRequest");

                    b.HasIndex("ClientUserId");

                    b.HasIndex("FriendId");

                    b.ToTable("FriendRequest", (string)null);
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.GroupChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MajorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("BLOB");

                    b.Property<int>("UniversityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("pk_Tbl");

                    b.HasIndex("MajorId");

                    b.HasIndex("UniversityId");

                    b.ToTable("GroupChat", (string)null);
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.GroupMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FromClientUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupChatId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("pk_GroupMessage");

                    b.HasIndex("FromClientUserId");

                    b.HasIndex("GroupChatId");

                    b.ToTable("GroupMessage", (string)null);
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Major", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("pk_Major");

                    b.ToTable("Major", (string)null);
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FromClientUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ToClientUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("pk_Message");

                    b.HasIndex("FromClientUserId");

                    b.HasIndex("ToClientUserId");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("pk_Note");

                    b.HasIndex("ClientUserId");

                    b.ToTable("Note", (string)null);
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FromClientUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ToClientUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("pk_Notification");

                    b.HasIndex("FromClientUserId");

                    b.HasIndex("NotificationTypeId");

                    b.HasIndex("ToClientUserId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.NotificationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("pk_NotificationType");

                    b.ToTable("NotificationType", (string)null);
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Photo")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("pk_Post");

                    b.HasIndex("ClientUserId");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("pk_Skill");

                    b.ToTable("Skill", (string)null);
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("pk_University");

                    b.ToTable("University", (string)null);
                });

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Domain.Entities.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Article", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.ArticleType", "ArticleType")
                        .WithMany("Articles")
                        .HasForeignKey("ArticleTypeId")
                        .IsRequired()
                        .HasConstraintName("fk_Article_ArticleType");

                    b.HasOne("StudyBuddy.Domain.Entities.ClientUser", "ClientUser")
                        .WithMany("Articles")
                        .HasForeignKey("ClientUserId")
                        .HasConstraintName("fk_Article_ClientUser");

                    b.Navigation("ArticleType");

                    b.Navigation("ClientUser");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.AspNetRoleClaim", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.AspNetUserClaim", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.AspNetUser", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.AspNetUserLogin", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.AspNetUser", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.AspNetUserToken", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.AspNetUser", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.City", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("fk_City_Country");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.ClientFile", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.ClientUser", "ClientUser")
                        .WithMany("ClientFiles")
                        .HasForeignKey("ClientUserId")
                        .IsRequired()
                        .HasConstraintName("fk_ClientFile_ClientUser");

                    b.Navigation("ClientUser");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.ClientUser", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.City", "City")
                        .WithMany("ClientUsers")
                        .HasForeignKey("CityId")
                        .HasConstraintName("fk_ClientUser_City");

                    b.HasOne("StudyBuddy.Domain.Entities.Country", "Country")
                        .WithMany("ClientUsers")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("fk_ClientUser_Country");

                    b.HasOne("StudyBuddy.Domain.Entities.Major", "Major")
                        .WithMany("ClientUsers")
                        .HasForeignKey("MajorId")
                        .HasConstraintName("fk_ClientUser_Major");

                    b.HasOne("StudyBuddy.Domain.Entities.University", "University")
                        .WithMany("ClientUsers")
                        .HasForeignKey("UniversityId")
                        .HasConstraintName("fk_ClientUser_University");

                    b.HasOne("StudyBuddy.Domain.Entities.AspNetUser", "User")
                        .WithMany("ClientUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_ClientUser_AspNetUsers");

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("Major");

                    b.Navigation("University");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.ClientUserAvailableDay", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.ClientUser", "ClientUser")
                        .WithMany("ClientUserAvailableDays")
                        .HasForeignKey("ClientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Domain.Entities.Day", "Day")
                        .WithMany("ClientUserAvailableDays")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientUser");

                    b.Navigation("Day");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.ClientUserGroupChat", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.ClientUser", "ClientUser")
                        .WithMany("ClientUserGroupChats")
                        .HasForeignKey("ClientUserId")
                        .IsRequired()
                        .HasConstraintName("fk_ClientUserGroupChat_ClientUser");

                    b.HasOne("StudyBuddy.Domain.Entities.GroupChat", "GroupChat")
                        .WithMany("ClientUserGroupChats")
                        .HasForeignKey("GroupChatId")
                        .IsRequired()
                        .HasConstraintName("fk_ClientUserGroupChat_GroupChat");

                    b.Navigation("ClientUser");

                    b.Navigation("GroupChat");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.ClientUserLikeFeed", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.ClientUser", "ClientUser")
                        .WithMany("ClientUserLikeFeeds")
                        .HasForeignKey("ClientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyBuddy.Domain.Entities.Feed", "Feed")
                        .WithMany("ClientUserLikeFeeds")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientUser");

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.ClientUserSkill", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.ClientUser", "ClientUser")
                        .WithMany("ClientUserSkills")
                        .HasForeignKey("ClientUserId")
                        .IsRequired()
                        .HasConstraintName("fk_ClientUserSkill_ClientUser");

                    b.HasOne("StudyBuddy.Domain.Entities.Skill", "Skill")
                        .WithMany("ClientUserSkills")
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("fk_ClientUserSkill_Skill");

                    b.Navigation("ClientUser");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Event", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.ClientUser", "ClientUser")
                        .WithMany("Events")
                        .HasForeignKey("ClientUserId")
                        .IsRequired()
                        .HasConstraintName("fk_Event_ClientUser");

                    b.Navigation("ClientUser");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Feed", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.ClientUser", "ClientUser")
                        .WithMany("Feeds")
                        .HasForeignKey("ClientUserId")
                        .IsRequired()
                        .HasConstraintName("fk_Feed_ClientUser");

                    b.Navigation("ClientUser");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.FeedReplay", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.Feed", "Feed")
                        .WithMany("FeedReplays")
                        .HasForeignKey("FeedId")
                        .IsRequired()
                        .HasConstraintName("fk_FeedReplay_Feed");

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Friend", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.ClientUser", "SecondFriend")
                        .WithMany("SecondFriendFriendNavigations")
                        .HasForeignKey("FirstFriendId")
                        .IsRequired()
                        .HasConstraintName("fk_Friend_ClientUser_0");

                    b.HasOne("StudyBuddy.Domain.Entities.ClientUser", "FirstFriend")
                        .WithMany("FirstFriendClientUsers")
                        .HasForeignKey("FirstFriendId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirstFriend");

                    b.Navigation("SecondFriend");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.FriendRequest", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.ClientUser", "ClientUser")
                        .WithMany("FriendRequestClientUsers")
                        .HasForeignKey("ClientUserId")
                        .IsRequired()
                        .HasConstraintName("fk_FriendRequest_ClientUser");

                    b.HasOne("StudyBuddy.Domain.Entities.ClientUser", "Friend")
                        .WithMany("FriendRequestFriends")
                        .HasForeignKey("FriendId")
                        .IsRequired()
                        .HasConstraintName("fk_FriendRequest_ClientUser_0");

                    b.Navigation("ClientUser");

                    b.Navigation("Friend");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.GroupChat", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.Major", "Major")
                        .WithMany("GroupChats")
                        .HasForeignKey("MajorId")
                        .IsRequired()
                        .HasConstraintName("fk_GroupChat_Major");

                    b.HasOne("StudyBuddy.Domain.Entities.University", "University")
                        .WithMany("GroupChats")
                        .HasForeignKey("UniversityId")
                        .IsRequired()
                        .HasConstraintName("fk_GroupChat_University");

                    b.Navigation("Major");

                    b.Navigation("University");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.GroupMessage", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.ClientUser", "FromClientUser")
                        .WithMany("GroupMessages")
                        .HasForeignKey("FromClientUserId")
                        .IsRequired()
                        .HasConstraintName("fk_GroupMessage_ClientUser");

                    b.HasOne("StudyBuddy.Domain.Entities.GroupChat", "GroupChat")
                        .WithMany("GroupMessages")
                        .HasForeignKey("GroupChatId")
                        .IsRequired()
                        .HasConstraintName("fk_GroupMessage_GroupChat");

                    b.Navigation("FromClientUser");

                    b.Navigation("GroupChat");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Message", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.ClientUser", "FromClientUser")
                        .WithMany("MessageFromClientUsers")
                        .HasForeignKey("FromClientUserId")
                        .IsRequired()
                        .HasConstraintName("fk_Message_ClientUser_0");

                    b.HasOne("StudyBuddy.Domain.Entities.ClientUser", "ToClientUser")
                        .WithMany("MessageToClientUsers")
                        .HasForeignKey("ToClientUserId")
                        .IsRequired()
                        .HasConstraintName("fk_Message_ClientUser");

                    b.Navigation("FromClientUser");

                    b.Navigation("ToClientUser");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Note", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.ClientUser", "ClientUser")
                        .WithMany("Notes")
                        .HasForeignKey("ClientUserId")
                        .IsRequired()
                        .HasConstraintName("fk_Note_ClientUser");

                    b.Navigation("ClientUser");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Notification", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.ClientUser", "FromClientUser")
                        .WithMany("NotificationFromClientUsers")
                        .HasForeignKey("FromClientUserId")
                        .IsRequired()
                        .HasConstraintName("fk_Notification_ClientUser_0");

                    b.HasOne("StudyBuddy.Domain.Entities.NotificationType", "NotificationType")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypeId")
                        .IsRequired()
                        .HasConstraintName("fk_Notification_NotificationType");

                    b.HasOne("StudyBuddy.Domain.Entities.ClientUser", "ToClientUser")
                        .WithMany("NotificationToClientUsers")
                        .HasForeignKey("ToClientUserId")
                        .IsRequired()
                        .HasConstraintName("fk_Notification_ClientUser");

                    b.Navigation("FromClientUser");

                    b.Navigation("NotificationType");

                    b.Navigation("ToClientUser");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Post", b =>
                {
                    b.HasOne("StudyBuddy.Domain.Entities.ClientUser", "ClientUser")
                        .WithMany("Posts")
                        .HasForeignKey("ClientUserId")
                        .IsRequired()
                        .HasConstraintName("fk_Post_ClientUser");

                    b.Navigation("ClientUser");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.ArticleType", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserTokens");

                    b.Navigation("ClientUsers");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.City", b =>
                {
                    b.Navigation("ClientUsers");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.ClientUser", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("ClientFiles");

                    b.Navigation("ClientUserAvailableDays");

                    b.Navigation("ClientUserGroupChats");

                    b.Navigation("ClientUserLikeFeeds");

                    b.Navigation("ClientUserSkills");

                    b.Navigation("Events");

                    b.Navigation("Feeds");

                    b.Navigation("FirstFriendClientUsers");

                    b.Navigation("FriendRequestClientUsers");

                    b.Navigation("FriendRequestFriends");

                    b.Navigation("GroupMessages");

                    b.Navigation("MessageFromClientUsers");

                    b.Navigation("MessageToClientUsers");

                    b.Navigation("Notes");

                    b.Navigation("NotificationFromClientUsers");

                    b.Navigation("NotificationToClientUsers");

                    b.Navigation("Posts");

                    b.Navigation("SecondFriendFriendNavigations");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("ClientUsers");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Day", b =>
                {
                    b.Navigation("ClientUserAvailableDays");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Feed", b =>
                {
                    b.Navigation("ClientUserLikeFeeds");

                    b.Navigation("FeedReplays");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.GroupChat", b =>
                {
                    b.Navigation("ClientUserGroupChats");

                    b.Navigation("GroupMessages");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Major", b =>
                {
                    b.Navigation("ClientUsers");

                    b.Navigation("GroupChats");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.NotificationType", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.Skill", b =>
                {
                    b.Navigation("ClientUserSkills");
                });

            modelBuilder.Entity("StudyBuddy.Domain.Entities.University", b =>
                {
                    b.Navigation("ClientUsers");

                    b.Navigation("GroupChats");
                });
#pragma warning restore 612, 618
        }
    }
}
